# Question 1

In [1]:
import numpy as np
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [2]:
a = []
b = []
for i in range(5):
    x = int(input("enter the elements for list 1\n"))
    a.append(x)
for i in range(5):
    x= int (input("enter the elements for list 2\n"))
    b.append(x)
arr1 = np.array(a)
arr2 = np.array(b)

arr3= np.concatenate((arr1,arr2))
print(arr3)

s = np.sort(arr3)
print(s)

enter the elements for list 1
8
enter the elements for list 1
2
enter the elements for list 1
4
enter the elements for list 1
5
enter the elements for list 1
1
enter the elements for list 2
2
enter the elements for list 2
9
enter the elements for list 2
5
enter the elements for list 2
4
enter the elements for list 2
10
[ 8  2  4  5  1  2  9  5  4 10]
[ 1  2  2  4  4  5  5  8  9 10]


# Question 3

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
d = arr.ndim
print(d)
s = arr.size
print(s)

2
6


# Question 4

In [4]:
arr = np.arange(10)
d = arr.shape
print("shape",d)

rowarr = arr[np.newaxis, :]
row = rowarr.shape
print("2D array in row",row)

colarr = arr[:, np.newaxis]
col = colarr.shape
print(" 2d Array in column",col)


arr = np.arange(10)
s = arr.shape
print("\nShape",s)


row_arr = np.expand_dims(arr, axis=0)
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise
col_arr = np.expand_dims(arr, axis=1)
print("\nShape of 2d Array in column major :",col_arr.shape)

shape (10,)
2D array in row (1, 10)
 2d Array in column (10, 1)

Shape (10,)

Shape of 2d Array in row major : (1, 10)

Shape of 2d Array in column major : (10, 1)


# Question 5

In [5]:
arr_1 = np.square([1, 2, 3, 4, 5])
arr_2 = np.square([6, 7, 8, 9, 10])


print("Horizontal Append :", np.hstack((arr_1, arr_2)))
print("Vertical Append :", np.vstack((arr_1, arr_2)))

Horizontal Append : [  1   4   9  16  25  36  49  64  81 100]
Vertical Append : [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# Question 6

In [8]:
arr1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])

unique, counts = np.unique(arr1, return_counts=True)

arr = np.asarray((unique, counts)).T

print(arr)

[[ 1  2]
 [ 2  2]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  1]
 [10  1]
 [16  1]
 [25  1]]


In [ ]:
-